version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build:
      context: ./go-battle
      dockerfile: api.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./go-battle:/usr/src/app
    command: air -c .air.toml

  cerveau:
    build:
      context: ./cerveau
      dockerfile: Dockerfile
    volumes:
      - ./cerveau:/cerveau:delegated

  web:
    build:
      dockerfile: ./go-battle-web/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - WATCHPACK_POLLING=true
    volumes:
      - ./go-battle-web:/usr/src/app/go-battle-web:delegated

volumes:
  db:
    driver: local
